CREATE TYPE MPAA_RATING AS ENUM ('G', 'PG', 'PG_13', 'NC_17');

CREATE TYPE COUNTRY AS ENUM ('GERMANY', 'SPAIN', 'NORTH_KOREA', 'JAPAN');

CREATE TABLE COORDINATES
(
    ID                 SERIAL               PRIMARY KEY,
    X                  DOUBLE PRECISION     NOT NULL CHECK (X > -593),
    Y                  BIGINT               NOT NULL CHECK (Y > -148)
);

CREATE TABLE PERSON
(
    ID                 SERIAL               PRIMARY KEY,
    NAME               VARCHAR(256)         NOT NULL CHECK (CHAR_LENGTH(NAME) > 0),
    HEIGHT             BIGINT               CHECK (HEIGHT > 0),
    PASSPORT_ID        VARCHAR(32)          NOT NULL UNIQUE,
    NATIONALITY        COUNTRY              NOT NULL
);

CREATE TABLE MOVIE
(
    ID                 SERIAL               PRIMARY KEY,
    NAME               VARCHAR(256)         NOT NULL CHECK (CHAR_LENGTH(NAME) > 0),
    COORDINATES        INTEGER              REFERENCES COORDINATES (ID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    CREATION_DATE      DATE                 NOT NULL,
    OSCARS_COUNT       INTEGER              NOT NULL CHECK (OSCARS_COUNT > 0),
    GOLDEN_PALM_COUNT  BIGINT               CHECK (GOLDEN_PALM_COUNT > 0),
    TOTAL_BOX_OFFICE   DOUBLE PRECISION     NOT NULL CHECK (TOTAL_BOX_OFFICE > 0),
    MPAA_RATING        MPAA_RATING          NOT NULL,
    SCREEN_WRITER      INTEGER              REFERENCES PERSON (ID) ON UPDATE CASCADE ON DELETE CASCADE
);